### ISSUE TITLE
sponsored display is not available on EU region

### ISSUE THREAD

**Issue by Amirsohail007** [amzn/amazon-marketing-stream-examples#1]
I have Talked to Amazon Team they are saying that github repo is outdated, and sponsored display is available in EU region.
I have given the conversation image link below:  
![image](https://github.com/amzn/amazon-marketing-stream-examples/assets/93404305/38df453b-c0a3-49af-a91d-357ec8186147)

**Comment by kdwivedi13** [comment]
**Stream reference application now supports all sponsored ads datasets.**
Our Stream reference application now supports all sponsored ads datasets. For a full list of supported datasets, see our [README](https://github.com/amzn/amazon-marketing-stream-examples#supported-datasets).
Happy Streaming!
